### ISSUE TITLE
Hey dude！Is there a problem with the example project you gave?

### ISSUE THREAD

**Issue by justicbro** [npuv5pp/Simuro5v5#1]
We use the example project you gave to run the platform, press the "Begin" button of the platform, but the platform does not respond.

**Comment by ykai55** [comment]
You need to run your strategy with [V5DLLAdapter](https://github.com/npuv5pp/V5DLLAdapter) first so that platform could connect to the strategy.
Read the readme for more details.

**Comment by justicbro** [comment]
We tried, the platform also played animation, but the robot still didn't start running.

**Comment by ykai55** [comment]
Sorry, I didn't notice your reply. Have you already solved this problem?
