### ISSUE TITLE
Is there a problem with your program?

### ISSUE THREAD

**Issue by cantlookaway** [npuv5pp/Simuro5v5#2]
The function of manual place has no effect. Once you start pressing resume, the robot will return to its original position.

**Comment by ykai55** [comment]
Sorry. In previous version, anytime platform received a new placement it will try to correct that to a regular placement, even it is from manual placement.
The new version has fixed this issus, please try.

**Comment by cantlookaway** [comment]
Is there a packaged version of the new version of the platform?
